### ISSUE TITLE
How to use timestamps for simulations / convert back to timestamp units

### ISSUE THREAD

**Issue by draconar** [AnthonyEbert/queuecomputer#35]
Hi,
I'm a noob to queue theory, and I'm trying to use queuecomputer to calculate waiting time for historical data. I have timestamps for arrival, start of service, end of service and departure. But I can't see how to use the timestamps as inputs. The results are not matching the data I'm feeding the algorithm...

Also, is there any wait to do the simulations and convert those to HH:MM ?

**Comment by AnthonyEbert** [comment]
queuecomputer just uses numbers rather than date-time data. I recommend lubridate https://lubridate.tidyverse.org/ for converting to and from date-time data. You need to convert to numbers before using queuecomputer. 

Anyway it sounds like you don't even need queuecomputer, can't you just say that 
wait time = start_of_service - arrival 
?

queuecomputer is made for the situation where you have the times at which customers arrive (arrival times), and the time it takes each customer to be served (service times). You have a lot more information.

**Comment by draconar** [comment]
Hi Anthony, thank you very much for your prompt assistance.
It did work. Once I converted the dates to numbers equivalent to the time of arrival and the servicing, I managed to simulate the queues.

One nice side-effect of using queuecomputer was that I managed to understand how the queues worked for my system, even though I could compute the waiting times directly. I managed to played with the number of servers, and to to have an idea on how the 'on the ground' operations are working. Kudos to you.

But my goal is to 'predict' waiting time for near future/current utilization of the system. Any tips?

Is there an email address I could reach you directly?

Cheers!
